apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aas
  template:
    metadata:
      labels:
        app: aas
    spec:
      containers:
        - name: aas
          image: enzomaria/aas
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/aas
      restartPolicy: Always
